### ISSUE TITLE
16. Further explorations

### ISSUE THREAD

**Issue by joancolmenerodev** [googlecodelabs/android-room-with-a-view#101]
Just in case someone wants to add the testing for the code-lab as it says on the 16 chapter. 

> The solution code includes unit tests for the Room database. Testing is beyond the scope of this code-lab. Take a look at the code if you are interested.

They are not using `coroutines` and `suspend fun` on their example, so just in case you guys want to implement it, you can copy what their are doing but add 

`runBlocking{YOURDAOCALL}` whenever you want to test a `suspend fun`

**Comment by peter-budo** [comment]
Indeed @joancolmenerodev just run into this "problem" bit of explanation here https://medium.com/androiddevelopers/room-coroutines-422b786dc4c5. @florina-muntenescu can you guys align codelab and repo please or can we do PRs instead of report bugs?

**Comment by florina-muntenescu** [comment]
Currently the code and the tests are using coroutines.
