### ISSUE TITLE
Step 15: minor highlight issue in variable name

### ISSUE THREAD

**Issue by odahcam** [googlecodelabs/android-room-with-a-view#102]
It is like this:
![image](https://user-images.githubusercontent.com/3942006/81183543-a8954a80-8f85-11ea-8110-49da1fc8defa.png)
(`WordViewModel` a`llWords`)

It should be like this: `WordViewModel` `allWords`

**Comment by florina-muntenescu** [comment]
Fixed. Thanks for reporting
