### ISSUE TITLE
ViewModelProvider throw exception when newInstance a ContactViewModel

### ISSUE THREAD

**Issue by ennbou** [googlecodelabs/android-room-with-a-view#103]
java.lang.InstantiationException: java.lang.Class<ContactViewModel> has no zero argument constructor

I have one constructor have an argument, 
` public ContactViewModel(Application application)`

**Comment by squm** [comment]
confirming ViewModel constructor is never called, and implementing Factory did help as described here : [https://stackoverflow.com/a/46704702/2000057](https://stackoverflow.com/a/46704702/2000057)

**Comment by florina-muntenescu** [comment]
Using `by viewModels` in the codelab now
