### ISSUE TITLE
Issue in Step :  15  there is no such method ViewModelProvider(this) 

### ISSUE THREAD

**Issue by sureshmaidaragi1919** [googlecodelabs/android-room-with-a-view#106]
`wordViewModel = ViewModelProvider(this).get(WordViewModel::class.java)
`

In above line, **there is no such method** `ViewModelProvider(this)` instead we should update it to as follows

`wordViewModel =  ViewModelProviders.of(this).get(WordViewModel::class.java)
`
 
dependency used version is   
`  implementation "androidx.lifecycle:lifecycle-viewmodel:2.1.0"
`

**Comment by masonstevens95** [comment]
Hi, I don't think this solution works. I still get a runtime error. This article helped me fix the issue https://medium.com/koderlabs/viewmodel-with-viewmodelprovider-factory-the-creator-of-viewmodel-8fabfec1aa4f

we need to make a new class, WordViewModelFactory then pass that to ViewModelProvider

**Comment by florina-muntenescu** [comment]
Using `by viewModels` now.
