### ISSUE TITLE
Ressources missing

### ISSUE THREAD

**Issue by Marloman** [googlecodelabs/android-room-with-a-view#108]
Found three little mistakes in this Codelab.

Step 11: "android:contentDescription="@string/add_word""
This string ressource is missing in strings.xml

Step 12: "Run your app to make sure everything works."
Cannot run now because of missing "@dimen/big_padding" in Step 11, which will be added in Step 14.

Step 14: ""@dimen/min_height" is missing in dimens.xml

**Comment by jcrbsa** [comment]
@Marloman , It seems that It wasn't inform to add this dimension resource in values/dimens.xml in the step (14. Add NewWordActivity):

`<dimen name="min_height">48dp</dimen>`

But, you can look at in github repository [](https://github.com/googlecodelabs/android-room-with-a-view/blob/master/app/src/main/res/values/dimens.xml)

**Comment by florina-muntenescu** [comment]
Fixed meanwhile. Thanks for reporting!
