### ISSUE TITLE
App does not save data

### ISSUE THREAD

**Issue by post799** [googlecodelabs/android-room-with-a-view#109]
I followed instructions and it works until you close application and reopen it. It saves nothing what I typed.
I even downloaded source code thinking maybe I made a mistake somewhere but no, even Google's own app from the source code doesn't save anything. I thought that was the point of this tutorial - to save data using Room?

**Comment by masonstevens95** [comment]
I agree, this is broken. I feel like I wasted a lot of time here...

**Comment by post799** [comment]
Yes, that's why I started my own YouTube channel.
https://youtu.be/N2qGmG8VxQc

I go step by step to become Associate Android Developer.  Recorded 8 videos
so far. There will be around 50 videos/subjects. After that you can get
Android Developer Certification from Google. Watch my first video ! Or all
of them of course

**Comment by masonstevens95** [comment]
Cool, I'll look into it. When are you planning on getting to Room?

**Comment by post799** [comment]
I go by Google's own Study Guide step by step . Here is the link to the
study guide by Google https://developers.google.com/certification
I am on Android core still. Room would be in Data Management section, so
about 20 videos/subjects away. I am DONE jumping around from place to
place, man ! Haha

**Comment by post799** [comment]
Sorry, this is link to study guide
https://developers.google.com/certification/associate-android-developer/study-guide

**Comment by wmadao11** [comment]
It's expected behaviour. Since followed with [STEP 13](https://codelabs.developers.google.com/codelabs/android-room-with-a-view-kotlin/#12), database will be reset every time the app restarted. 
You can change to override the `onCreate` method in `RoomDatabase.Callback` rather than `onOpen`, and then the data will be stored.

```kotlin
   private class WordDatabaseCallback(
       private val scope: CoroutineScope
   ) : RoomDatabase.Callback() {

       // this will be called every time database opened
       override fun onOpen(db: SupportSQLiteDatabase) {
           super.onOpen(db)
           INSTANCE?.let { database ->
               scope.launch {
                   var wordDao = database.wordDao()

                   // Delete all content here.
                   wordDao.deleteAll()

                   // Add sample words.
                   var word = Word("Hello")
                   wordDao.insert(word)
                   word = Word("World!")
                   wordDao.insert(word)

                   // TODO: Add your own words!
                   word = Word("TODO!")
                   wordDao.insert(word)
               }
           }
       }
   }
```

**Comment by florina-muntenescu** [comment]
Codelab updated to use `onCreate`
