### ISSUE TITLE
ViewModel creation Crash

### ISSUE THREAD

**Issue by salami09076** [googlecodelabs/android-room-with-a-view#110]
`wordViewModel=ViewModelProvider(this, ViewModelProvider.AndroidViewModelFactory(application)).get(WordViewModel::class.java)
` is not working

`        wordViewModel=ViewModelProvider(this).get(WordViewModel::class.java)
` is also not working

**Comment by almosting** [comment]
I have the same problem

**Comment by almosting** [comment]
I fix this problem

in build.gardle:
apply plugin: 'kotlin-kapt'

kapt "androidx.room:room-compiler:2.2.5"
implementation "androidx.room:room-ktx:2.2.5"
in WordRoomDatabase:
@Database(entities = [Word::class], version = 1)
