### ISSUE TITLE
Update gradle depedencies

### ISSUE THREAD

**Issue by absh959595** [googlecodelabs/android-room-with-a-view#114]
At the time of writing, the lifecycle gradle dependencies mentioned in the [codelab tutorial](https://codelabs.developers.google.com/codelabs/android-room-with-a-view/#3) are

```
// Lifecycle components
implementation "androidx.lifecycle:lifecycle-extensions:$rootProject.archLifecycleVersion"
annotationProcessor "androidx.lifecycle:lifecycle-compiler:$rootProject.archLifecycleVersion"
```

at which AndroidStudio 4.0 pssts..

```
Use the Lifecycle Java 8 API provided by the lifecycle-common-java8 library instead of Lifecycle annotations for faster incremental build. 
```
not to mention the advice [here](https://developer.android.com/jetpack/androidx/releases/lifecycle) to use the individual components instead of extensions

Proposing change to 

```
implementation "androidx.lifecycle:lifecycle-viewmodel:$lifecycle_version"
implementation "androidx.lifecycle:lifecycle-livedata:$lifecycle_version"
implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"
```

or something similar

**Comment by florina-muntenescu** [comment]
Fixed. Thanks for reporting

**Comment by grndvl1** [comment]
So what is the solution?  I am getting this and no one seems to know the right answer.  I am using 
`    // live data + view model
    kapt 'androidx.lifecycle:lifecycle-compiler:2.3.1'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1"
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.3.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.3.1'
`
 and it is telling me to 

"Use the Lifecycle Java 8 API provided by the lifecycle-common-java8 library inst..."
