### ISSUE TITLE
Room sample uses deprecated dependency

### ISSUE THREAD

**Issue by pdmurty** [googlecodelabs/android-room-with-a-view#116]
https://developer.android.com/jetpack/androidx/releases/lifecycle
 says 
The APIs in lifecycle-extensions have been deprecated. Instead, add dependencies for the specific Lifecycle artifacts you need.
But the code lab sample still uses the deprecated extension dependency.

**Comment by florina-muntenescu** [comment]
Fixed. Thanks for reporting
