### ISSUE TITLE
Warning "Redundant SAM-constructor" and Error "Unable to start Activity ComponentInfo"

### ISSUE THREAD

**Issue by Venjoy1230** [googlecodelabs/android-room-with-a-view#118]
I followed the tutorial until the step 15. 
Just so you know, I adapted the tutorial to a personal project I'm working on for my studies. 
When I try to run my app on AndroidStudio, I get the error "
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.flyintoazeroth/com.example.flyintoazeroth.ChooseTrip}: java.lang.RuntimeException: Cannot create an instance of class com.example.flyintoazeroth.TripViewModel" .
In my MainActivity (here called "ChooseTrip"), I get a warning on the "Observer {words -> words?.let {adapter.setWords(it) }" section.
The observer is blackened and AndroidStudio tells me that "Observer" is a redundant SAM-constructor. 
I'm not that great in programming at the moment, especially in Kotlin and the use of Room. 
If anyone has any idea about why this might be an issue, I'll be grateful.

**Comment by florina-muntenescu** [comment]
Issue not applicable. The codelab was refactored meanwhile.
