### ISSUE TITLE
condition checks should not be at the same level

### ISSUE THREAD

**Issue by samcoding2019** [googlecodelabs/android-room-with-a-view#119]
these 2 conditions shouldn't be at the same if block:

if (requestCode == newWordActivityRequestCode && resultCode == Activity.RESULT_OK)

it makes more sense to do something like this:
if (requestCode == newWordActivityRequestCode) {
   if (resultCode == Activity.RESULT_OK) {
      ...
   }
   else {
      ...
   }

**Comment by florina-muntenescu** [comment]
Codelab code refactored meanwhile.
