### ISSUE TITLE
	Gradle sync failed:

### ISSUE THREAD

**Issue by gagan100o** [googlecodelabs/android-room-with-a-view#120]
I am getting an error every time when I start android studio . that is...=

Gradle sync failed: Could not connect to server [66817f96-796f-482d-80d5-2e2885153383 port:63864, addresses:[/127.0.0.1]]. Tried addresses: [/127.0.0.1].
				Consult IDE log for more details (Help | Show Log) (1 m 14 s 927 ms)

**Comment by florina-muntenescu** [comment]
issue unrelated to the codelab
