### ISSUE TITLE
InstantiationException

### ISSUE THREAD

**Issue by RaheesNetCommLabs** [googlecodelabs/android-room-with-a-view#121]
On the below line in MainActivity, getting crash

wordViewModel = ViewModelProvider(this).get(WordViewModel::class.java)

Caused by: java.lang.InstantiationException: java.lang.Class<com.example.namelist.WordViewModel> has no zero argument constructor

**Comment by GC-Xi** [comment]
This can be fix by adding
```
    implementation "androidx.activity:activity:$rootProject.activityVersion"
```

**Comment by florina-muntenescu** [comment]
The codelab was refactored meanwhile. Issue not applicable anymore.
