### ISSUE TITLE
Error Android Room with a View - Java

### ISSUE THREAD

**Issue by Swordox972** [googlecodelabs/android-room-with-a-view#129]
I got an error in the MainActivity at mWordViewModel = new ViewModelProvider(this).get(WordViewModel.class);. It is metioned in the step 15 "Connect with the data". The error is : ViewModel has no zero argument constructor.

So I change  mWordViewModel = new ViewModelProvider(this).get(WordViewModel.class) to 
mWordViewModel = new ViewModelProvider(this,ViewModelProvider.AndroidViewModelFactory.getInstance(this.getApplication()))
                .get(WordViewModel.class); and it worked

**Comment by Iain22** [comment]
Thank you Swordox972, that works for me too.

**Comment by nightshifty** [comment]
Thank you very much, fixed it for me.

**Comment by allonb** [comment]
Thanks! That worked.

**Comment by ShermanMohler** [comment]
I was able, with this fix, to get the Java example running. As mentioned in a different issue the Java version of this example is not available on GitHub

**Comment by florina-muntenescu** [comment]
Fixed in #181 and #182 . Thanks for reporting!
