### ISSUE TITLE
Invalidation tracker is initialized twice :/.

### ISSUE THREAD

**Issue by tmehta813** [googlecodelabs/android-room-with-a-view#138]
When I migrate the database version, same error happens E/ROOM: Invalidation tracker is initialized twice.
even if I don't migrate this error is coming again and again, 
When I had single table, it didn't arrive. as I added one more table, it started arriving.
And my app never comes in foreground , it stays in background forever, What should I do ?

Room version : 2.2.5

**Comment by florina-muntenescu** [comment]
This doesn't seem like a problem with the codelab. Please create an issue on the [Room issue tracker](https://issuetracker.google.com/issues/new?component=413107&template=1096568).
