### ISSUE TITLE
Section '11. Add XML layout' generates multiple "Android resource linking failed"

### ISSUE THREAD

**Issue by TAFKAMW** [googlecodelabs/android-room-with-a-view#139]
When building, the values of the 3 items below all turn red and show build error "Android resource linking failed".

    <style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

The same error is thrown for these entries in other files:
`android:padding="@dimen/big_padding"`
`android:contentDescription="@string/add_word"`

**Comment by florina-muntenescu** [comment]
This error seems to appear when something is wrong in the xml. can you ensure that you don't have any duplicate lines in the xmls?
