### ISSUE TITLE
App Crashes due to wrong appCompatVersion value

### ISSUE THREAD

**Issue by nandinib1999** [googlecodelabs/android-room-with-a-view#146]
Error: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;

The version has to be changed from '1.2.0' to '1.3.0-alpha02' to make the app work.

ext {
    appCompatVersion = '1.3.0-alpha02'
    constraintLayoutVersion = '2.0.4'
    coreTestingVersion = '2.1.0'
    lifecycleVersion = '2.2.0'
    materialVersion = '1.2.1'
    roomVersion = '2.2.5'
    // testing
    junitVersion = '4.13.1'
    espressoVersion = '3.1.0'
    androidxJunitVersion = '1.1.2'
}

These values may be used for running the app without errors.

**Comment by florina-muntenescu** [comment]
Fixed in #181 and #182 . Thanks for reporting!
