### ISSUE TITLE
On step 14, text refers to onOpen() of the RoomDatabase.Callback, but it is really onCreate()

### ISSUE THREAD

**Issue by oscardelgado** [googlecodelabs/android-room-with-a-view#149]

**Comment by Len512** [comment]
Yes. 

Also in step 14, the code given after "Here is the code for creating the callback within the WordRoomDatabase class:", is different than the code given after "Here is what the final code should look like:".

**Comment by florina-muntenescu** [comment]
Fixed. Thanks for reporting!
