### ISSUE TITLE
Cannot create an instance of class com.example.android.roomwordssample.WordViewModel

### ISSUE THREAD

**Issue by Dheerendra007** [googlecodelabs/android-room-with-a-view#150]
Cannot create an instance of class com.example.android.roomwordssample.WordViewModel

**Comment by icymunchhhiip** [comment]
`mWordViewModel = new ViewModelProvider(this, new ViewModelProvider.AndroidViewModelFactory(getApplication())).get(WordViewModel.class);`

https://github.com/googlecodelabs/android-room-with-a-view/issues/143#issuecomment-738410458

**Comment by florina-muntenescu** [comment]
Fixed in #181 and #182 . Thanks for reporting!
