### ISSUE TITLE
The Example keeps sptoping

### ISSUE THREAD

**Issue by EricsHalloWorld** [googlecodelabs/android-room-with-a-view#152]
Hey Guys thx for the tutorial,

I just wanted to see my mistakes. 
I tried runing the Example App in the Android Studio VM multible times, restarted everything, but as the title says it keeps stopping.

What any suggestion why the example doesen't work?
Do I have to download additional software?
thx for helping.

**Comment by EricsHalloWorld** [comment]
I tried Kotlin and this worked.

**Comment by swve** [comment]
I too have this issue, the apps keeps closing
