### ISSUE TITLE
[Question] How to being able to delete words ?

### ISSUE THREAD

**Issue by dleurs** [googlecodelabs/android-room-with-a-view#157]
Hello !

I am  beginning with Android, and trying to get my head around Activity/Adatper/Dao/LiveData/Application/Intent/ViewModel ...
I am on the kotlin branch, commit df178215fc7

I would like to being able to delete word, but I am stuck on how to access the ViewModel from the ListAdapter.<br/>
From the UI, I just added a button in recyclerview_item.xml<br/>
In WordListAdapter :
```
    override fun onBindViewHolder(holder: WordViewHolder, position: Int) {
        val current = getItem(position)
        holder.bind(current.name)
        holder.itemView.apply {
            val buttonDelete = findViewById<Button>(R.id.button)
            buttonDelete.setOnClickListener {
                //wordViewModel.delete(current)
                // How to access View Model ?
            }
        }
    }
```
How to access wordViewModel from ListAdapter ? Should I rather send an Intent ? But how ?

Thank you

**Comment by MahmoudMabrok** [comment]
you have two ways 
- send ViewModel as parameter with list adapter (bad solution)
- send message to fragment that contains ViewModel using (callbacks, rxjava, etc) (best solution)

**Comment by dleurs** [comment]
@MahmoudMabrok Thank you for your response. Can I use Intent to send information from ViewHolder to main Activity ?

**Comment by dleurs** [comment]
@MahmoudMabrok  Thank you for your message. I have try with callbacks/interface, not successful :/  <br/>
I have coded a new file :  
```
interface TodoInterface {
    fun onItemClick(todo: Todo);
}
```
Then added in MainActivity 
```
class MainActivity : AppCompatActivity(), TodoInterface {
...
    override fun onItemClick(todo: Todo) {
        todoViewModel.delete(todo)
    }
```
But I don't know what to do in TodoListAdapter
```
class TodoListAdapter(todoInterface: TodoInterface) : ListAdapter<Todo, TodoListAdapter.TodoViewHolder>(TODOS_COMPARATOR)
...
// Cannot put todoInterface in argument of "override fun onBindViewHolder(holder: TodoViewHolder, position: Int)" 
// 
```
<a href="https://github.com/dleurs/android-kotlin-todo-app">My project</a> is slitly different, Todo instead of word

**Comment by MahmoudMabrok** [comment]
i did a PR to your project @dleurs

**Comment by dleurs** [comment]
Thank you very much ! 

I wasn't not aware of the data:Todo? technique to get the actual todo, and using the init / data?.let to access it inside TodoViewHolder
```
        var data:Todo? = null
        
        init {
            deleteTodo.setOnClickListener { 
                data?.let {
                    todoInterface.onItemClick(it)
                }
            }
        }
```

That makes the difference between a code that run and one that does not run :p
