### ISSUE TITLE
Words not deleted from database on startup

### ISSUE THREAD

**Issue by oschubert** [googlecodelabs/android-room-with-a-view#164]
I downloaded and imported the solution code.  From the comments in WordRoomDatabase.kt I expected that the words added to the database would always be deleted when the application restarts.  They don't!

**Comment by matale** [comment]
Only if there is a migration taking place, a migration is when you change the DB version, so if you change the version here
`@Database(entities = [Word::class], version = 1)`
Any new words should be deleted and the original word list reloaded.

**Comment by florina-muntenescu** [comment]
The codelab doesn't say that the database is deleted when the application restarts, but rather when the version is increased.
