### ISSUE TITLE
4. Update Gradle files - link not working

### ISSUE THREAD

**Issue by AndreSand** [googlecodelabs/android-room-with-a-view#167]
Page not found for step 3. Add the packagingOptions block inside the android block to exclude the atomic functions module from the package and prevent warnings.

link return 404 https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html

**Comment by florina-muntenescu** [comment]
Fixed in #181 and #182 . Thanks for reporting!
Code was removed
