### ISSUE TITLE
How to Save/Read From Split Tables?

### ISSUE THREAD

**Issue by zxcvbnm3057** [googlecodelabs/android-room-with-a-view#170]
I have a database in my app that has almost 100 thousands records. So I'm going to split it to several tables. But it seem that every @entity class linked to one special database. So how can I use room to link that database I needed? And the program won't know which database is going to read until user type in some information.

**Comment by florina-muntenescu** [comment]
Not an issue with the codelab. Please use this issue tracker for issues with the codelab.
