### ISSUE TITLE
Step #4 kotlin_version is missing

### ISSUE THREAD

**Issue by RomanTsisyk** [googlecodelabs/android-room-with-a-view#171]
You missed kotlin_version  here:
ext {
    activityVersion = '1.1.0'
    appCompatVersion = '1.2.0'
    constraintLayoutVersion = '2.0.2'
    coreTestingVersion = '2.1.0'
    coroutines = '1.3.9'
    lifecycleVersion = '2.2.0'
    materialVersion = '1.2.1'
    roomVersion = '2.2.5'
    // testing
    junitVersion = '4.13.1'
    espressoVersion = '3.1.0'
    androidxJunitVersion = '1.1.2'
}

**Comment by florina-muntenescu** [comment]
Fixed. Thanks for reporting!
