### ISSUE TITLE
 java.lang.Class<com.example.android.roomwordssample.WordViewModel> has no zero argument constructor

### ISSUE THREAD

**Issue by canyetismis** [googlecodelabs/android-room-with-a-view#173]
Hello, I just downloaded the source code and when I ran it without making any changes I came across this error. It happens when the ViewModel instance in the Main Activity is being initialised. Am I missing something or is this an ongoing issue?

**Comment by chetan-tuteja** [comment]
I have fixed this issue [here with this PR](https://github.com/googlecodelabs/android-room-with-a-view/pull/174). It is an issue with Lifecycle version 2.2.0, just see the PR and make required changes and you should be good to go. More discussion [here](https://stackoverflow.com/questions/60451458/possible-to-access-androidviewmodel-of-activity-via-fragment/60451554#60451554).

**Comment by florina-muntenescu** [comment]
Fixed in #181 and #182 . Thanks for reporting!
