### ISSUE TITLE
On Step 9 it errors: "No type arguments expected for class Flow"

### ISSUE THREAD

**Issue by FarzanKh** [googlecodelabs/android-room-with-a-view#177]
![Screenshot 2021-05-30 101429](https://user-images.githubusercontent.com/14272565/120113557-db315880-c12f-11eb-8480-38cbfd1672cd.png)

This seems to fix the issue:

![Screenshot 2021-05-30 101533](https://user-images.githubusercontent.com/14272565/120113589-ff8d3500-c12f-11eb-8edd-386d60e4433d.png)

**Comment by florina-muntenescu** [comment]
You have the wrong `Flow` class added originally - it looks like you imported `java.util.concurrent.Flow`
