### ISSUE TITLE
Codelab documentation imports wrong RecyclerView

### ISSUE THREAD

**Issue by JeffinWithYa** [googlecodelabs/android-room-with-a-view#22]
This is not a problem with this repository but a problem with the CodeLab for this project. I didn't know where else to report this. On Step 10 of the code lab they tell you to copy/paste in a RecyclerView, but it is from the wrong library. The project should use the androidx version, as is used in this repository. 

Issue on this page:
https://codelabs.developers.google.com/codelabs/android-room-with-a-view/#9 

From Code Lab in above link: 

Replace:
<android.support.v7.widget.RecyclerView
   android:id="@+id/recyclerview"
   android:layout_width="match_parent"
   android:layout_height="match_parent"
   android:background="@android:color/darker_gray"
   tools:listitem="@layout/recyclerview_item" />

with:
    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/recyclerview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@android:color/darker_gray"
        tools:listitem="@layout/recyclerview_item" />

**Comment by florina-muntenescu** [comment]
Thanks for reporting this. Fixed.
