### ISSUE TITLE
[missingtype]: element 'com.example.xxxx.xxxxx.xxxRoomDatabase' references a type that is not present

### ISSUE THREAD

**Issue by msgaba** [googlecodelabs/android-room-with-a-view#223]
I used the same steps to create a project of my own, but it's giving the above error and I am unable to build it. Please let me know if anyone know where the issue might be or the fix for the same

**Comment by WazirxDax** [comment]
Any solution?

**Comment by yinxiucheng** [comment]
I has the save problem

**Comment by msgaba** [comment]
@yinxiucheng @WazirxDax 
Remove this part of code from your App level Gradle, followed by invalidating caches and restarting your studio, and you'll be good to go

> configurations { cleanedAnnotations compile.exclude group: 'org.jetbrains', module: 'annotations' }
