### ISSUE TITLE
Codelab WordViewModel class issue.

### ISSUE THREAD

**Issue by SasivardanANB** [googlecodelabs/android-room-with-a-view#24]
In the WordViewModel ( _kotlin version code_) we are having `private val repository: WordRepository` so the **repository** not accessible in the following line.
```
fun insert(word: Word) = viewModelScope.launch {
        repository.insert(word)
    }
```
Compilation error
Any suggestions for the fixes or workaround for the mentioned issue.

**Comment by DAGalpin** [comment]
Both of these need to be in the WordViewModel class so the ViewModel can encapsulate the repository.
