### ISSUE TITLE
Manifest merger failed : Attribute application@appComponentFactory 

### ISSUE THREAD

**Issue by mohoshin47** [googlecodelabs/android-room-with-a-view#25]
last 3 day i am showing this problem,how can i solve it.this problem here 

Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-21:19 to override.

  i  am using this gradle 

 apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 28
    buildToolsVersion "29.0.2"
    defaultConfig {
        applicationId "com.mohoshin.myapplication"
        minSdkVersion 17
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.google.firebase:firebase-database:19.0.0'

    implementation 'com.google.firebase:firebase-core:17.2.0'
    implementation 'com.google.firebase:firebase-messaging:20.0.0'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

**Comment by edwinkapkei** [comment]
The new firebase versions require androidx to run. You are getting the error because your project still uses .support* libraries and you can't mix the two.
 Migrate to androidx or use the older firebase versions. 
Check the link for firebase change logs: https://firebase.google.com/support/release-notes/android#all_firebase_sdks_for_android

**Comment by DAGalpin** [comment]
Thanks edwinkapkei for answering this one.  In general, try to keep issues here limited to the code in question.
