### ISSUE TITLE
Deprecated class and function use

### ISSUE THREAD

**Issue by perihanmirkelam** [googlecodelabs/android-room-with-a-view#27]
"14. Connect with the data" section from codelab,

`mWordViewModel = ViewModelProviders.of(this).get(WordViewModel.class);`

> `ViewModelProviders` class and `of` function is deprecated.

https://codelabs.developers.google.com/codelabs/android-room-with-a-view/#13

**Comment by DAGalpin** [comment]
Fixed.  Thanks!
