### ISSUE TITLE
WordListAdapter Method is Private

### ISSUE THREAD

**Issue by sschueller** [googlecodelabs/android-room-with-a-view#28]
In my android studio it appears the default is to mark methods as private. So I had to do the following:

```
public WordListAdapter(Context context) { mInflater = LayoutInflater.from(context); }
```

**Comment by JHandal7** [comment]
package com.example.android.roomwordsample

import android.R
import android.content.Context
import android.view.ViewGroup
import android.view.LayoutInflater
import android.view.View
import android.widget.TextView
import androidx.recyclerview.widget.RecyclerView

class WordListAdapter internal constructor(
    context: Context
) : RecyclerView.Adapter<WordListAdapter.WordViewHolder>() {

    private val inflater: LayoutInflater = LayoutInflater.from(context)
    private  var words = emptyList<Word>() // Cached copy of words

    inner class WordViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
        val wordItemView: TextView = itemView.findViewById(R.id.textView)
    }

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): WordViewHolder {
        val itemView = inflater.inflate(R.layout.recyclerview_item, parent, false)
        return WordViewHolder(itemView)
    }

    override fun onBindViewHolder(holder: WordViewHolder, position: Int) {
        val current = words[position]
        holder.wordItemView.text = current.word
    }

    internal fun setWords(words: List<Word>) {
        this.words = words
        notifyDataSetChanged()
    }

    override fun getItemCount() = words.size
}

**Comment by JHandal7** [comment]
The resource R.layout.recyclerview_item is present 
recyclerview_item.xml

I got a build error: 
failed linking file resources.

**Comment by DAGalpin** [comment]
The WordListAdapter is marked as public within the codelab.

'''
public class WordListAdapter extends RecyclerView.Adapter<WordListAdapter.WordViewHolder> {
'''
