### ISSUE TITLE
when i use this room framework, it always show the error

### ISSUE THREAD

**Issue by xxxcrel** [googlecodelabs/android-room-with-a-view#33]
> Could not resolve all files for configuration ':data:debugAnnotationProcessorClasspath'. 
> Could not download kotlinx-metadata-jvm.jar (org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.0.5)
> Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-metadata-jvm/0.0.5/kotlinx-metadata-jvm-0.0.5.jar'. 
> Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-metadata-jvm/0.0.5/kotlinx-metadata-jvm-0.0.5.jar'.

**Comment by DAGalpin** [comment]
I believe this was corrected by updating the Gradle build plugin.  Thank you!
