### ISSUE TITLE
Dao getAllWords()

### ISSUE THREAD

**Issue by felipemesturini** [googlecodelabs/android-room-with-a-view#35]
@Dao
interface WordDao {

    @Query("SELECT * from word_table ORDER BY word ASC")
    fun getAllWords(): LiveData<List<Word>> //Correct
    fun getAllWords(): List<Word> //Wrong

    @Insert(onConflict = OnConflictStrategy.IGNORE)
    suspend fun insert(word: Word)

    @Query("DELETE FROM word_table")
    suspend fun deleteAll()
}

**Comment by DAGalpin** [comment]
We being by using just List<Word> so we can introduce LiveData later --- it's possible that this issue was fixed prior to my looking at it.

**Comment by DarkOhms** [comment]
I'm so confused.  Mine is Flow???
