### ISSUE TITLE
A constant declared without being initialized.

### ISSUE THREAD

**Issue by brytlab** [googlecodelabs/android-room-with-a-view#37]
A Constant should be initialized when being declared and Constant cannot be reinitialized as done in this code. 

In this use case, `wordItemView` must not be a constant. 

`private final TextView wordItemView;`

```
 private WordViewHolder(View itemView) {
           super(itemView);
           wordItemView = itemView.findViewById(R.id.textView);
       }
```

**Comment by Calinou** [comment]
Declaring properties as `final` is allowed if you initialize them in the constructor (which is the case here). Of course, you can't set them to a different value after initializing them.

**Comment by brytlab** [comment]
Yh, You're right
