### ISSUE TITLE
Nullable String warning in `OnActivityResult` sample

### ISSUE THREAD

**Issue by garanj** [googlecodelabs/android-room-with-a-view#38]
In the **Connect with the data** step, the following sample is given:

```
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
  // ...
  val word = Word(it.getStringExtra(NewWordActivity.EXTRA_REPLY))
  // ...
}
```

I get a warning for this code:  

```
Type mismatch: inferred type is String? but String was expected
```

**Comment by DAGalpin** [comment]
Fixed in ad53dcbd398fcac7d2259fac6e50ad513ba8210c.  It now does
`intentData?.getStringExtra(NewWordActivity.EXTRA_REPLY)?.let {
    val word = Word(data.getStringExtra(NewWordActivity.EXTRA_REPLY))	                val 
    word = Word(it)'
