### ISSUE TITLE
AndroidViewModel requires ViewModelProvider.Factory

### ISSUE THREAD

**Issue by jaykallen** [googlecodelabs/android-room-with-a-view#42]
Add this class:
class MyViewModelFactory (private var application: Application): ViewModelProvider.Factory {
    override fun <T : ViewModel?> create(modelClass: Class<T>): T {
        return modelClass.getConstructor(Application::class.java).newInstance(application)
    }
}
and this line to MainActivity:
val viewModelFactory = MyViewModelFactory(application)

**Comment by kubilayciftci** [comment]
Hi, are you sure this solution ?  I wrote all codes, i added part you said but I got an error this case and not solve this problem.

**Comment by jaykallen** [comment]
I have uploaded my code to here:   https://github.com/jaykallen/RoomSample2
Perhaps its the version of the libraries I'm working on.  Here are the
versions I added:
    // Room
    implementation "androidx.room:room-runtime:2.2.1"
    implementation "androidx.room:room-ktx:2.2.1"
    kapt "androidx.room:room-compiler:2.2.1"
    androidTestImplementation "androidx.room:room-testing:2.2.1"
    // Lifecycle
    implementation "androidx.lifecycle:lifecycle-extensions:2.1.0"
    androidTestImplementation "androidx.arch.core:core-testing:2.1.0"
    // ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.1.0"
    // Coroutines
    api "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.2"
    // UI
    implementation "com.google.android.material:material:1.0.0"

**Comment by kubilayciftci** [comment]
Thanks. I will check my code now.

**Comment by DAGalpin** [comment]
The final sample doesn't require the factory, but there was a mistake in the final code snapshot in the codelab.  It has been corrected to:
```
 wordViewModel = ViewModelProvider(this).get(WordViewModel::class.java)
```
