### ISSUE TITLE
ViewModelProvider vs ViewModelProviders

### ISSUE THREAD

**Issue by Tomroke** [googlecodelabs/android-room-with-a-view#43]
Android Room with a View - Kotlin, 14. Connect with the data.

The first example of using the ViewModelProvider uses the following line of code "wordViewModel = ViewModelProvider(this).get(WordViewModel::class.java)" which is wrong.

While the complete example uses the following line " wordViewModel = ViewModelProviders.of(this).get(WordViewModel::class.java)" which works properly.

**Comment by kubilayciftci** [comment]
In this case the use is correct 

`wordViewModel = ViewModelProvider(this).get(WordViewModel::class.java)`

because this part "of()" removed.

**Comment by DAGalpin** [comment]
Thanks for catching that.  Fixed and updated.

**Comment by cherylli** [comment]
Now it says `wordViewModel = ViewModelProvider(this).get(WordViewModel::class.java) ` does not work, my app crashed on create. 

> ViewModelProviders.of(this).get(WordViewModel::class.java)" which works properly.

This works for me too.
