### ISSUE TITLE
Data is not persistent

### ISSUE THREAD

**Issue by GunnarBernsteinHH** [googlecodelabs/android-room-with-a-view#44]
As this is a Room example it is very frustrating to see, the data is not stored.

Every time the program is restartet, the data is lost.

I downloaded the database from the emulator which does not seem to have any contents.

I do not get any errors in LogCat and the insert statement finishes OK.

For tests I use this github repository, same with manually created in tutorial.

Nexus 5 Emulator with API 26 and 28.

**Comment by DAGalpin** [comment]
This is by design to make it easier to debug.   There is a comment explaining how to make the data persistent.

```
            // If you want to keep data through app restarts,
            // comment out the following block
            databaseWriteExecutor.execute(() -> {
```
for the Java version or

```
                // If you want to keep the data through app restarts,
                // comment out the following line.
                INSTANCE?.let { database ->
                    scope.launch(Dispatchers.IO) {
                        populateDatabase(database.wordDao())
                    }
                }
```
for the Kotlin one.
