### ISSUE TITLE
archLifecycleVersion = '2.2.0-rc02'

### ISSUE THREAD

**Issue by andrewsleeman24** [googlecodelabs/android-room-with-a-view#45]
archLifecycleVersion = '2.2.0-rc2'
should be:
archLifecycleVersion = '2.2.0-rc02'
ie the zero is required in "rc02"

**Comment by mansur1989** [comment]
I had same problem

**Comment by tangxiaocheng** [comment]
I encountered the same problem.
I hate this kind of tiny mistake.

**Comment by sv-git-hub** [comment]
As of 1/7/2020 this I could not get Gradle to sync without updating to the following, specifically "rc03":

archLifecycleVersion = '2.2.0-rc03'

**Comment by florina-muntenescu** [comment]
Fixed meanwhile
