### ISSUE TITLE
The Kotlin version has a Java example in Step 4

### ISSUE THREAD

**Issue by thomashorta** [googlecodelabs/android-room-with-a-view#48]
The Step 4 (Create an Entity) has a **Tip** block at the end which contains a Java example, even though the CodeLab is specific for Kotlin.

The snippet of Java Code can be confusing to newcomers as it actually contradicts the paragraph above it (where it says that _"Every property that's stored in the database needs to have public visibility"_). And the snipped shows private Java properties being annotated.

**Comment by augustgrun** [comment]
I agree that this is misleading. Should be as follows for consistency:

```
@Entity(tableName = "word_table")
data class Word (@PrimaryKey(autoGenerate = true) val id: Int,
                 @ColumnInfo(name = "word") val word: String)
```

**Comment by florina-muntenescu** [comment]
Fixed
