### ISSUE TITLE
Error in callback onCreate() in Step 14 [Java]

### ISSUE THREAD

**Issue by Marvel0usx** [googlecodelabs/android-room-with-a-view#50]
In onCreate() method below RecyclerView code block, when getting a ViewModel from ViewModelProviders, the code should be 
`mWordViewModel = ViewModelProviders.of(this).get(WordViewModel.class);`
according to [https://developer.android.com/topic/libraries/architecture/viewmodel.html](url)

**Comment by florina-muntenescu** [comment]
Use [ViewModelProvider](https://developer.android.com/reference/androidx/lifecycle/ViewModelProvider)
