### ISSUE TITLE
Typo in "6. The LiveData class"

### ISSUE THREAD

**Issue by augustgrun** [googlecodelabs/android-room-with-a-view#52]
https://codelabs.developers.google.com/codelabs/android-room-with-a-view-kotlin/#5

Last link: [Components: LifeData and Lifecycle ](https://www.youtube.com/watch?v=OMcDk2_4LSk&index=8&list=PLWz5rJ2EKKc9mxIBd0DRw9gwXuQshgmn2)

"LifeData".... Is this a new class we are developing for FitBit? :)

**Comment by djnotes** [comment]
Agreed. The error is still there!  

![image](https://imgur.com/uanvXAC)

**Comment by florina-muntenescu** [comment]
Fixed
