### ISSUE TITLE
If the Sample intends to have a "Create Repository" section, it should feature the problem that the Repository is meant to solve.

### ISSUE THREAD

**Issue by Zhuinden** [googlecodelabs/android-room-with-a-view#53]
Currently the Repository does nothing except delegate method calls to the DAO.

In this case, Repository is not needed, as there is no second data source to use.

In fact, the application might not even ever have a remote data source.

Then why is there a Repository?

Also, same problem applies to BasicSample, so I'm not sure why that is linked in the footnotes.

**Comment by florina-muntenescu** [comment]
That is correct, the Repository just forwards the calls. But the role of the codelab is to explain an app architecture. The codelab text explains the role of the Repository and why this approach was taken for the codelab
