### ISSUE TITLE
Wrong Dependencie Version for Lifecycle

### ISSUE THREAD

**Issue by lilalukas** [googlecodelabs/android-room-with-a-view#55]
Hi,

when you try to copy and paste to code, it will not work, since the Constructor of ViewModelProvider does not exists.
`myViewModel = new ViewModelProvider(this).get(MyViewModel.class);` 

You have to chance the dependency-version to
`archLifecycleVersion = '2.2.0-beta01'` 
as it is written in the src code, but not in the CodeLab.

**Comment by jenileechen800** [comment]
Is this the only change you made?

I changed my dependency version, but I'm still getting an error

<img width="690" alt="Screen Shot 2019-12-16 at 5 11 59 PM" src="https://user-images.githubusercontent.com/46302505/70955904-339d9480-2027-11ea-8c2e-47a3579cf6ea.png">

**Comment by arynchoong** [comment]
I've got the gradle working for the latest versions as below

ext {
    roomVersion = '2.2.3'
    archLifecycleVersion = '2.2.0-rc02'
    coreTestingVersion = '2.1.0'
    materialVersion = '1.0.0'
}

**Comment by sv-git-hub** [comment]
As of 1/7/2020, archLifecycleVersion 2.2.0-rc02 not longer worked, or at least not for me. I found that the latest is now archLifecycleVersion = '2.2.0-rc03'... which it then worked.

**Comment by florina-muntenescu** [comment]
Use 2.2.0
