### ISSUE TITLE
ViewModelProvider Constructor Not Applicable

### ISSUE THREAD

**Issue by jenileechen800** [googlecodelabs/android-room-with-a-view#56]
Can anyone help me resolve this bug?

<img width="499" alt="Screen Shot 2019-12-16 at 5 28 10 PM" src="https://user-images.githubusercontent.com/46302505/70957010-955efe00-2029-11ea-8772-485eae07c155.png">
![Uploading Screen Shot 2019-12-16 at 5.11.59 PM.png…]()

**Comment by jenileechen800** [comment]
<img width="690" alt="Screen Shot 2019-12-16 at 5 11 59 PM" src="https://user-images.githubusercontent.com/46302505/70957273-6bf2a200-202a-11ea-8311-22045beaa9da.png">

**Comment by jhancock1975** [comment]
I got the same compile error. I set `archLifecycleVersion = '2.2.0-rc02'.  ` Do you have to use `2.2.0-beta01`?

**Comment by sv-git-hub** [comment]
You may have to use this version now (as of 1/7/2020): archLifecycleVersion = '2.2.0-rc03'

**Comment by moussa-b** [comment]
Hi, i had the same problem I replaced 
`wordViewModel = ViewModelProvider(this).get(WordViewModel::class.java)`
by
`wordViewModel = ViewModelProviders.of(this).get(WordViewModel::class.java)`

**Comment by florina-muntenescu** [comment]
Use 2.2.0 version and [`ViewModelProvider`](https://developer.android.com/reference/androidx/lifecycle/ViewModelProvider)
