### ISSUE TITLE
Incorrect reference in SQL statement on step 4 and 14

### ISSUE THREAD

**Issue by sv-git-hub** [googlecodelabs/android-room-with-a-view#59]
Incorrect SQL statement on steps 4 (Create the Dao) and in referencing on step 14 (Summary). Referencing to "word" errors. Otherwise, I was able to run this app tutorial successfully on the current tutorial version (as of 1/7/2020). I'm coding Java not Kotlin.

**Incorrect**: "SELECT * from word_table ORDER BY word ASC"
**Correct**: "SELECT * from word_table ORDER BY mWord ASC"   <-- word to mWord

**Comment by zawawimanja** [comment]
@NonNull
    @ColumnInfo(name = "word")
    private String mWord;


I think there is no problem with this.

**Comment by sv-git-hub** [comment]
My apologies, you are correct. I overlooked identitifying the column name (i.e. name = "word".

Thanks for checking and bring it to my attention.
