### ISSUE TITLE
Wrong ViewModel Implementation in the point 14-Connect with the data

### ISSUE THREAD

**Issue by abdullah-alialdin** [googlecodelabs/android-room-with-a-view#62]
In onCreate() below the RecyclerView code block, get a ViewModel from the ViewModelProvider.
mWordViewModel = new ViewModelProvider(this).get(WordViewModel.class);
the code should be 
mWordViewModel = ViewModelProviders.of(this).get(WordViewModel.class);

**Comment by iamrohitkiransawai** [comment]
@abdullah-alialdin Thank you for raising this issue. It has solved my problem. I was doing again and again same thing and was using same code provided in codelab which was not working and tried to find the correct code but I failed and finally I came to your reported issue and your code worked for me and my believed that Google developers also make mistakes.

**Comment by androidDeveloper851** [comment]
@iamrohitkiransawai n 2.2.0 version viewModelProviders is marked ad deprecated so imho the google's code is correct :).
