### ISSUE TITLE
Java code in Kotlin codelab

### ISSUE THREAD

**Issue by abarska** [googlecodelabs/android-room-with-a-view#65]
https://codelabs.developers.google.com/codelabs/android-room-with-a-view-kotlin/#3

Tip: You can autogenerate unique keys by annotating the primary key as follows:

@Entity(tableName = "word_table")
public class Word {

@PrimaryKey(autoGenerate = true)
private int id;

@NonNull
private String word;
//..other fields, getters, setters
}

**Comment by augustgrun** [comment]
Should be changed to the following:
```
@Entity(tableName = "word_table")
data class Word (@PrimaryKey(autoGenerate = true) val id: Int,
                 @ColumnInfo(name = "word") val word: String)
```

**Comment by florina-muntenescu** [comment]
Fixed
