### ISSUE TITLE
LiveData with room

### ISSUE THREAD

**Issue by androidDeveloper851** [googlecodelabs/android-room-with-a-view#68]
I'm not sure it's the problem with this demo but ... :) 
I added stetho integration to this app and when app was running I addes some words to database using chrome (chrome://inspect). This new data appears in the app only when i rerun app - it's correct way how LiveData observers works ?

**Comment by florina-muntenescu** [comment]
Room and LiveData integration is based on a callback that the database triggers when something is changed. Does the stetho integration makes that callback trigger? Closing this for now
