### ISSUE TITLE
Android Room with a View - Java

### ISSUE THREAD

**Issue by MSMurtaza** [googlecodelabs/android-room-with-a-view#70]
https://codelabs.developers.google.com/codelabs/android-room-with-a-view/index.html?index=..%2F..index#3

Each public property in the class represents a column in the table

public class Word {

   private String mWord;

   public Word(@NonNull String word) {this.mWord = word;}

   public String getWord(){return this.mWord;}
}

While it should be

Each private property/ property in the class represents a column in the table

**Comment by florina-muntenescu** [comment]
fixed
