### ISSUE TITLE
Typing Error

### ISSUE THREAD

**Issue by codeworship** [googlecodelabs/android-room-with-a-view#72]
There is an error on this page: https://codelabs.developers.google.com/codelabs/android-room-with-a-view-kotlin/index.html?index=..%2F..index#6

On the section: Implement the Room Database, point number 3. It is written: 
You make database provides its DAOs by creating an abstract "getter" method for each @Dao.
Thats a typing error. It should be something like: 
To make the database provide its DAOs ...

**Comment by florina-muntenescu** [comment]
Fixed
