### ISSUE TITLE
ViewModelProvider(this).get(WordViewModel::class.java) Crash

### ISSUE THREAD

**Issue by humanheima** [googlecodelabs/android-room-with-a-view#75]
```
wordViewModel = ViewModelProvider(this).get(WordViewModel::class.java)
```
This code will cause crash.

**Comment by humanheima** [comment]
We should pass a `AndroidViewModelFactory` to ViewModelProvider , like this.
```
wordViewModel = ViewModelProvider(this,
                    ViewModelProvider.AndroidViewModelFactory(activity!!.application)
            ).get(WordViewModel::class.java)
```

**Comment by Dea10** [comment]
[StackOverFlow](https://stackoverflow.com/questions/52394416/cannot-create-an-instance-of-subclass-of-androidviewmodel)

`mWordViewModel = new ViewModelProvider(this, new ViewModelProvider.AndroidViewModelFactory(getApplication())).get(WordViewModel.class);`

**Comment by florina-muntenescu** [comment]
Issue not applicable. The codelab was refactored meanwhile.
