### ISSUE TITLE
Typing

### ISSUE THREAD

**Issue by noor-offl** [googlecodelabs/android-room-with-a-view#79]
[https://codelabs.developers.google.com/codelabs/android-room-with-a-view/#0](url)
There is confusion on the page linked above.
Check this following texts -
"You need to be familiar with _**Kotlin**_, object-oriented design concepts, and Android Development Fundamentals. In particular:"
But this codelab uses java.

**Comment by florina-muntenescu** [comment]
Fixed. Replaced with Java
