### ISSUE TITLE
In your build.gradle (Project: RoomWordsSample) file, add the version numbers to the end of the file, as given in the code below and then sync the project.

### ISSUE THREAD

**Issue by ksmaddle** [googlecodelabs/android-room-with-a-view#84]
ext {
    roomVersion = '2.2.1'
    archLifecycleVersion = '2.2.0-rc2'   SHOULD BE archLifecycleVersion = '2.2.0-rc02'
    coreTestingVersion = '2.1.0'
    materialVersion = '1.0.0'
}

**Comment by florina-muntenescu** [comment]
version changed to `2.2.0` meanwhile
