### ISSUE TITLE
Capitalization of keywords on 5: Create the DAO

### ISSUE THREAD

**Issue by espertus** [googlecodelabs/android-room-with-a-view#86]
On [5: Create the DAO](https://codelabs.developers.google.com/codelabs/android-room-with-a-view-kotlin/#4), "from" should be capitalized in SQL queries along with other SQL keywords that are already capitalized ("SELECT", "ORDER", "BY", etc.)

**Comment by gorkhalitarang** [comment]
Also in codelabs suspend is used for insert and deleteall. While in this repo its different. Can anyone explain what difference does it make? Also check my issue.

**Comment by florina-muntenescu** [comment]
Fixed. Thanks for reporting
