### ISSUE TITLE
Dimension resource used before definition

### ISSUE THREAD

**Issue by espertus** [googlecodelabs/android-room-with-a-view#88]
`@dimen/big_padding` is used in step [10: Add XML layout](https://codelabs.developers.google.com/codelabs/android-room-with-a-view-kotlin/#9) but not defined until [13: Add NewWordActivity](https://codelabs.developers.google.com/codelabs/android-room-with-a-view-kotlin/#12).

**Comment by gorkhalitarang** [comment]
@espertus Dont mention me just to give me tips for github. I can agree with the upvote and downvote but still. Also in step 4. 
@Entity(tableName = "word_table")
class Word(@PrimaryKey @ColumnInfo(name = "word") val word: String)

It should be data class()... Now tell me if this is not a mistake. Also check my the one i have posted...

**Comment by odahcam** [comment]
We have #98 and #99 that discuss the same issue.

**Comment by florina-muntenescu** [comment]
Fixed meanwhile. Thanks for reporting!
