### ISSUE TITLE
Definition of Abstract method in abstract class is not provided

### ISSUE THREAD

**Issue by mshoaib-murtaza** [googlecodelabs/android-room-with-a-view#94]
abstract class WordRoomDatabase extends RoomDatabase {

    abstract WordDao wordDao();
    ...
}

class WordRepository {

    private WordDao mWordDao;
    private LiveData<List<Word>> mAllWords;

    WordRepository(Application application) {
        WordRoomDatabase db = WordRoomDatabase.getDatabase(application);
        // definition of wordDao() isn't provided anywhere but called below
        mWordDao = db.wordDao();
        mAllWords = mWordDao.getAlphabetizedWords();
    }
...
}

**Comment by florina-muntenescu** [comment]
Room generates the implementation of `WordRoomDatabase`
