### ISSUE TITLE
Build Failed : need `ktx` artifact from Room as a dependency

### ISSUE THREAD

**Issue by pranitishettiwar** [googlecodelabs/android-room-with-a-view#96]
WordDao.java:21: error: To use Coroutine features, you must add `ktx` artifact from Room as a dependency. androidx.room:room-ktx:<version>

**Comment by pranitishettiwar** [comment]
I fixed it by adding to app build.gradle,  `implementation "androidx.room:room-ktx:$rootProject.roomVersion"`

**Comment by MackHartley** [comment]
+1 I also had this issue and also used this solution to fix it

**Comment by dmonorchio** [comment]
i confirm this solution but my compilation crash

**Comment by florina-muntenescu** [comment]
Fixed. Thanks for reporting

**Comment by LuuNgocLan** [comment]
Thanks for this solution!
